### ISSUE TITLE
Newest version of the application crashes when opening the Animus 

### ISSUE THREAD

**Issue by Ashragnorok** [VarsityPhysicist/FFXIVRelicTracker#2] opened 2020-09-15 02:29 UTC
Each time I have opened the animus tab the application closes without any informational message. I have removed the data file under .\Roaming, but the issue still occurs.

**Comment by VarsityPhysicist** [comment] 2020-09-15 11:50
Hey, are you still having this issue?

**Comment by Ashragnorok** [comment] 2020-09-15 14:54
Yes, testing version 1.5, I load up my character and try to open the animus tab and the app closes. pulled some information from the windows error log.

Faulting application name: FFXIVRelicTracker.exe, version: 1.0.0.0, time stamp: 0x5e9fbfa2
Faulting module name: KERNELBASE.dll, version: 10.0.19041.488, time stamp: 0x42f14898
Exception code: 0xe0434352
Fault offset: 0x00129962
Faulting process id: 0x4120
Faulting application start time: 0x01d68b700c1b1f9e
Faulting application path: C:\APPS\FFXIVRelicTracker\FFXIVRelicTracker.exe
Faulting module path: C:\Windows\System32\KERNELBASE.dll
Report Id: fddb73f6-a2eb-4786-bf2a-40d394e61d69
Faulting package full name: 
Faulting package-relative application ID: 

Application: FFXIVRelicTracker.exe
CoreCLR Version: 4.700.20.41105
.NET Core Version: 3.1.8
Description: The process was terminated due to an unhandled exception.
Exception Info: System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index')
   at System.Collections.Generic.List`1.get_Item(Int32 index)
   at FFXIVRelicTracker.ARR.ArrHelpers.ArrInfo.ReturnCreatureNames(Int32 bookIndex) in C:\Users\lataj\source\repos\FFXIVRelicTracker\ARR\ArrHelpers\ArrInfo.cs:line 283
   at FFXIVRelicTracker.ARR.Animus.AnimusViewModel.ReadBooks() in C:\Users\lataj\source\repos\FFXIVRelicTracker\ARR\Animus\AnimusViewModel.cs:line 369
   at FFXIVRelicTracker.ARR.Animus.AnimusViewModel.LoadAvailableJobs() in C:\Users\lataj\source\repos\FFXIVRelicTracker\ARR\Animus\AnimusViewModel.cs:line 540
   at FFXIVRelicTracker.ViewModels.ArrViewModel.ChangeViewModel(IPageViewModel viewModel) in C:\Users\lataj\source\repos\FFXIVRelicTracker\ARR\ArrViewModel.cs:line 141
   at FFXIVRelicTracker.ViewModels.ArrViewModel.<get_ChangePageCommand>b__5_0(Object p) in C:\Users\lataj\source\repos\FFXIVRelicTracker\ARR\ArrViewModel.cs:line 95
   at FFXIVRelicTracker.Models.RelayCommand.Execute(Object parameter) in C:\Users\lataj\source\repos\FFXIVRelicTracker\Helpers\RelayCommand.cs:line 41
   at MS.Internal.Commands.CommandHelpers.CriticalExecuteCommandSource(ICommandSource commandSource, Boolean userInitiated)
   at System.Windows.Controls.Primitives.ButtonBase.OnClick()
   at System.Windows.Controls.Button.OnClick()
   at System.Windows.Controls.Primitives.ButtonBase.OnMouseLeftButtonUp(MouseButtonEventArgs e)
   at System.Windows.UIElement.OnMouseLeftButtonUpThunk(Object sender, MouseButtonEventArgs e)
   at System.Windows.Input.MouseButtonEventArgs.InvokeEventHandler(Delegate genericHandler, Object genericTarget)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.ReRaiseEventAs(DependencyObject sender, RoutedEventArgs args, RoutedEvent newEvent)
   at System.Windows.UIElement.OnMouseUpThunk(Object sender, MouseButtonEventArgs e)
   at System.Windows.Input.MouseButtonEventArgs.InvokeEventHandler(Delegate genericHandler, Object genericTarget)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.InputManager.ProcessInput(InputEventArgs input)
   at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
   at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.Run()
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at System.Windows.Application.Run()
   at FFXIVRelicTracker.App.Main() in C:\Users\lataj\source\repos\FFXIVRelicTracker\obj\Release\netcoreapp3.1\win-x86\App.g.cs:line 52

**Comment by VarsityPhysicist** [comment] 2020-09-15 15:44
Thank you, I believe I have replicated the issue and will look into fixing it once I get home from work.

My testing on new updates/releases has all been loading an existing character instead of creating a new one because I'm lazy so I wasn't seeing this happen. 

It looks like the issue is the animus tab tries to get the index of the initially selected book, and a new character has a book of null, so this causes the issue. At some point, this worked differently and did not cause the issue, so my loading/saving of the character I had previously made was not making the issue on my end.

I'll release 1.6 later today with this fixed and reply to this thread once that is done.

Thank you again for reporting this issue, and sorry for the problems

**Comment by VarsityPhysicist** [comment] 2020-09-15 23:01
I just released an update that should fix the issue, I tested this with creating a new character and from a character created from an older version.

Let me know if this fixes the bug and I can close this issue

**Comment by Ashragnorok** [comment] 2020-09-16 01:56
Looks like it is working as intended. Thank you

**Closed as completed** 2020-09-16 09:40 UTC
Labels: bug
